package EstadoApp;


/**
* EstadoApp/Estado.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Estado.idl
* lunes 29 de octubre de 2018 03:24:18 PM COT
*/

public interface Estado extends EstadoOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Estado
