package EstadoApp;


/**
* EstadoApp/EstadoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Estado.idl
* lunes 29 de octubre de 2018 03:24:18 PM COT
*/

public interface EstadoOperations 
{
  boolean insertarEstado (int id_estado, String nombre);
  boolean eliminarEstado (int id_estado);
  boolean actualizarEstado (int id_estado, String nombre);
  void shutdown ();
} // interface EstadoOperations
