package DetalleVentasApp;


/**
* DetalleVentasApp/_DetalleVentasStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DetalleVentas.idl
* miércoles 14 de noviembre de 2018 10:57:43 PM COT
*/

public class _DetalleVentasStub extends org.omg.CORBA.portable.ObjectImpl implements DetalleVentasApp.DetalleVentas
{

  public boolean insertarDetalleVentas (int id_venta, int id_articulo, int cantidad, int valor_unitario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarDetalleVentas", true);
                $out.write_long (id_venta);
                $out.write_long (id_articulo);
                $out.write_long (cantidad);
                $out.write_long (valor_unitario);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarDetalleVentas (id_venta, id_articulo, cantidad, valor_unitario        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarDetalleVentas

  public boolean eliminarDetalleVentas (int id_detalle)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarDetalleVentas", true);
                $out.write_long (id_detalle);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarDetalleVentas (id_detalle        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarDetalleVentas

  public boolean actualizarDetalleVentas (int id_detalle, int id_venta, int id_articulo, int cantidad, int valor_unitario)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarDetalleVentas", true);
                $out.write_long (id_detalle);
                $out.write_long (id_venta);
                $out.write_long (id_articulo);
                $out.write_long (cantidad);
                $out.write_long (valor_unitario);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarDetalleVentas (id_detalle, id_venta, id_articulo, cantidad, valor_unitario        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarDetalleVentas

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DetalleVentasApp/DetalleVentas:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _DetalleVentasStub
