package DetalleVentasApp;


/**
* DetalleVentasApp/DetalleVentasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DetalleVentas.idl
* miércoles 14 de noviembre de 2018 10:57:43 PM COT
*/

public interface DetalleVentasOperations 
{
  boolean insertarDetalleVentas (int id_venta, int id_articulo, int cantidad, int valor_unitario);
  boolean eliminarDetalleVentas (int id_detalle);
  boolean actualizarDetalleVentas (int id_detalle, int id_venta, int id_articulo, int cantidad, int valor_unitario);
  void shutdown ();
} // interface DetalleVentasOperations
