package DetalleVentasApp;


/**
* DetalleVentasApp/DetalleVentasPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DetalleVentas.idl
* miércoles 14 de noviembre de 2018 10:57:43 PM COT
*/

public abstract class DetalleVentasPOA extends org.omg.PortableServer.Servant
 implements DetalleVentasApp.DetalleVentasOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarDetalleVentas", new java.lang.Integer (0));
    _methods.put ("eliminarDetalleVentas", new java.lang.Integer (1));
    _methods.put ("actualizarDetalleVentas", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // DetalleVentasApp/DetalleVentas/insertarDetalleVentas
       {
         int id_venta = in.read_long ();
         int id_articulo = in.read_long ();
         int cantidad = in.read_long ();
         int valor_unitario = in.read_long ();
         boolean $result = false;
         $result = this.insertarDetalleVentas (id_venta, id_articulo, cantidad, valor_unitario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // DetalleVentasApp/DetalleVentas/eliminarDetalleVentas
       {
         int id_detalle = in.read_long ();
         boolean $result = false;
         $result = this.eliminarDetalleVentas (id_detalle);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // DetalleVentasApp/DetalleVentas/actualizarDetalleVentas
       {
         int id_detalle = in.read_long ();
         int id_venta = in.read_long ();
         int id_articulo = in.read_long ();
         int cantidad = in.read_long ();
         int valor_unitario = in.read_long ();
         boolean $result = false;
         $result = this.actualizarDetalleVentas (id_detalle, id_venta, id_articulo, cantidad, valor_unitario);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // DetalleVentasApp/DetalleVentas/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DetalleVentasApp/DetalleVentas:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DetalleVentas _this() 
  {
    return DetalleVentasHelper.narrow(
    super._this_object());
  }

  public DetalleVentas _this(org.omg.CORBA.ORB orb) 
  {
    return DetalleVentasHelper.narrow(
    super._this_object(orb));
  }


} // class DetalleVentasPOA
