package DetalleVentasApp;


/**
* DetalleVentasApp/DetalleVentas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DetalleVentas.idl
* miércoles 14 de noviembre de 2018 10:57:43 PM COT
*/

public interface DetalleVentas extends DetalleVentasOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DetalleVentas
