package ClienteApp;


/**
* ClienteApp/ClienteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cliente.idl
* miércoles 14 de noviembre de 2018 07:12:34 PM COT
*/

public interface ClienteOperations 
{
  boolean insertarCliente (int identificacion, String nombre, String telefono);
  boolean eliminarCliente (int id_cliente);
  boolean actualizarCliente (int id_cliente, int identificacion, String nombre, String telefono);
  void shutdown ();
} // interface ClienteOperations
