package ClienteApp;


/**
* ClienteApp/Cliente.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Cliente.idl
* miércoles 14 de noviembre de 2018 07:12:34 PM COT
*/

public interface Cliente extends ClienteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Cliente
