package ArticuloApp;


/**
* ArticuloApp/_ArticuloStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Articulo.idl
* lunes 29 de octubre de 2018 03:24:08 PM COT
*/

public class _ArticuloStub extends org.omg.CORBA.portable.ObjectImpl implements ArticuloApp.Articulo
{

  public boolean insertarArticulo (int id_articulo, int id_tpArticulo, int cantidad, int precio, String estado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarArticulo", true);
                $out.write_long (id_articulo);
                $out.write_long (id_tpArticulo);
                $out.write_long (cantidad);
                $out.write_long (precio);
                $out.write_wstring (estado);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarArticulo (id_articulo, id_tpArticulo, cantidad, precio, estado        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarArticulo

  public boolean eliminarArticulo (int id_articulo)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarArticulo", true);
                $out.write_long (id_articulo);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarArticulo (id_articulo        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarArticulo

  public boolean actualizarArticulo (int id_articulo, int id_tpArticulo, int cantidad, int precio, String estado)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarArticulo", true);
                $out.write_long (id_articulo);
                $out.write_long (id_tpArticulo);
                $out.write_long (cantidad);
                $out.write_long (precio);
                $out.write_wstring (estado);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarArticulo (id_articulo, id_tpArticulo, cantidad, precio, estado        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarArticulo

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ArticuloApp/Articulo:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ArticuloStub
