package ArticuloApp;


/**
* ArticuloApp/Articulo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Articulo.idl
* martes 13 de noviembre de 2018 10:35:12 PM COT
*/

public interface Articulo extends ArticuloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Articulo
