package ArticuloApp;

/**
* ArticuloApp/ArticuloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Articulo.idl
* martes 13 de noviembre de 2018 10:35:12 PM COT
*/

public final class ArticuloHolder implements org.omg.CORBA.portable.Streamable
{
  public ArticuloApp.Articulo value = null;

  public ArticuloHolder ()
  {
  }

  public ArticuloHolder (ArticuloApp.Articulo initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ArticuloApp.ArticuloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ArticuloApp.ArticuloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ArticuloApp.ArticuloHelper.type ();
  }

}
