package ArticuloApp;


/**
* ArticuloApp/Articulo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Articulo.idl
* lunes 29 de octubre de 2018 03:24:08 PM COT
*/

public interface Articulo extends ArticuloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Articulo
