package TpArticuloApp;


/**
* TpArticuloApp/TpArticuloHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TpArticulo.idl
* miércoles 31 de octubre de 2018 09:34:27 PM COT
*/

abstract public class TpArticuloHelper
{
  private static String  _id = "IDL:TpArticuloApp/TpArticulo:1.0";

  public static void insert (org.omg.CORBA.Any a, TpArticuloApp.TpArticulo that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TpArticuloApp.TpArticulo extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TpArticuloApp.TpArticuloHelper.id (), "TpArticulo");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TpArticuloApp.TpArticulo read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TpArticuloStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TpArticuloApp.TpArticulo value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TpArticuloApp.TpArticulo narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TpArticuloApp.TpArticulo)
      return (TpArticuloApp.TpArticulo)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TpArticuloApp._TpArticuloStub stub = new TpArticuloApp._TpArticuloStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static TpArticuloApp.TpArticulo unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TpArticuloApp.TpArticulo)
      return (TpArticuloApp.TpArticulo)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TpArticuloApp._TpArticuloStub stub = new TpArticuloApp._TpArticuloStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
