package TpArticuloApp;


/**
* TpArticuloApp/TpArticuloPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TpArticulo.idl
* miércoles 31 de octubre de 2018 09:34:27 PM COT
*/

public abstract class TpArticuloPOA extends org.omg.PortableServer.Servant
 implements TpArticuloApp.TpArticuloOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarTpArticulo", new java.lang.Integer (0));
    _methods.put ("eliminarTpArticulo", new java.lang.Integer (1));
    _methods.put ("actualizarTpArticulo", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TpArticuloApp/TpArticulo/insertarTpArticulo
       {
         String nombre = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarTpArticulo (nombre);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // TpArticuloApp/TpArticulo/eliminarTpArticulo
       {
         int id = in.read_long ();
         boolean $result = false;
         $result = this.eliminarTpArticulo (id);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // TpArticuloApp/TpArticulo/actualizarTpArticulo
       {
         int id = in.read_long ();
         String nombre = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarTpArticulo (id, nombre);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // TpArticuloApp/TpArticulo/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TpArticuloApp/TpArticulo:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public TpArticulo _this() 
  {
    return TpArticuloHelper.narrow(
    super._this_object());
  }

  public TpArticulo _this(org.omg.CORBA.ORB orb) 
  {
    return TpArticuloHelper.narrow(
    super._this_object(orb));
  }


} // class TpArticuloPOA
