package TpArticuloApp;


/**
* TpArticuloApp/TpArticulo.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TpArticulo.idl
* miércoles 31 de octubre de 2018 08:05:10 PM COT
*/

public interface TpArticulo extends TpArticuloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TpArticulo
