module VentasApp{
    interface Ventas{
        boolean insertarVentas(in long id_venta, in long cantidad, in long valor_total);
        boolean eliminarVentas(in long id_venta);
        boolean actualizarVentas(in long id_venta, in long cantidad, in long valor_total);
        oneway void shutdown();
    };

};
