module VentasApp{
    interface Ventas{
        boolean insertarVentas( in long id_cliente, in long cantidad_total, in long valor_total);
        boolean eliminarVentas(in long id_ventas);
        boolean actualizarVentas(in long id_ventas, in long id_cliente, in long cantidad_total, in long valor_total);
        oneway void shutdown();
    };

};
