module VentasApp{
    interface Ventas{
        boolean insertarVentas(in long id_ventas, in long id_tpArticulo, in long cantidad, in long precio, in wstring estado);
        boolean eliminarVentas(in long id_articulo);
        boolean actualizarVentas(in long id_articulo, in long id_tpArticulo, in long cantidad, in long precio, in wstring estado);
        oneway void shutdown();
    };

};
