package VentasApp;


/**
* VentasApp/VentasPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ventas.idl
* miércoles 14 de noviembre de 2018 01:58:19 AM COT
*/

public abstract class VentasPOA extends org.omg.PortableServer.Servant
 implements VentasApp.VentasOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarVentas", new java.lang.Integer (0));
    _methods.put ("eliminarVentas", new java.lang.Integer (1));
    _methods.put ("actualizarVentas", new java.lang.Integer (2));
    _methods.put ("shutdown", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // VentasApp/Ventas/insertarVentas
       {
         int id_cliente = in.read_long ();
         int cantidad_total = in.read_long ();
         int valor_total = in.read_long ();
         boolean $result = false;
         $result = this.insertarVentas (id_cliente, cantidad_total, valor_total);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // VentasApp/Ventas/eliminarVentas
       {
         int id_ventas = in.read_long ();
         boolean $result = false;
         $result = this.eliminarVentas (id_ventas);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // VentasApp/Ventas/actualizarVentas
       {
         int id_ventas = in.read_long ();
         int id_cliente = in.read_long ();
         int cantidad_total = in.read_long ();
         int valor_total = in.read_long ();
         boolean $result = false;
         $result = this.actualizarVentas (id_ventas, id_cliente, cantidad_total, valor_total);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // VentasApp/Ventas/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:VentasApp/Ventas:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Ventas _this() 
  {
    return VentasHelper.narrow(
    super._this_object());
  }

  public Ventas _this(org.omg.CORBA.ORB orb) 
  {
    return VentasHelper.narrow(
    super._this_object(orb));
  }


} // class VentasPOA
