package VentasApp;

/**
* VentasApp/VentasHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ventas.idl
* miércoles 14 de noviembre de 2018 01:58:19 AM COT
*/

public final class VentasHolder implements org.omg.CORBA.portable.Streamable
{
  public VentasApp.Ventas value = null;

  public VentasHolder ()
  {
  }

  public VentasHolder (VentasApp.Ventas initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = VentasApp.VentasHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    VentasApp.VentasHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return VentasApp.VentasHelper.type ();
  }

}
