package VentasApp;


/**
* VentasApp/Ventas.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ventas.idl
* miércoles 14 de noviembre de 2018 01:58:19 AM COT
*/

public interface Ventas extends VentasOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Ventas
