package VentasApp;


/**
* VentasApp/VentasOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Ventas.idl
* miércoles 14 de noviembre de 2018 01:58:19 AM COT
*/

public interface VentasOperations 
{
  boolean insertarVentas (int id_cliente, int cantidad_total, int valor_total);
  boolean eliminarVentas (int id_ventas);
  boolean actualizarVentas (int id_ventas, int id_cliente, int cantidad_total, int valor_total);
  void shutdown ();
} // interface VentasOperations
